image: python:3.11  

stages:
  - build
  - test
  - deploy
  - run

build:
  stage: build
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "Build completed"

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pytest tests/

deploy:
  stage: deploy
  script:
    - echo "Deploy stage - customize as needed"

run:
  stage: run
  script:
    - python customer_churn/customer_churn.py
